### PR TITLE
Adding spatial funcionality

### PR DESCRIPTION
**Pull request by jlevente**
These changes simply build changeset geometries if the `-g` option is enabled. Basic spatial index is also added. Requires postgis.

### CODE REVIEW

**Comment by ToeBee** [comment]
Woah I totally missed the notification of this pull request. Sorry about that. I'm giving it a run now.

**Comment by jlevente** [comment]
Haha, I forgot about it, too!
Let me know how it works out. I've been using my fork a few times to rebuild changeset geometries since I've made these changes with no issues at all.

**Comment by ToeBee** [comment]
Yeah, I actually used the geometry column in this branch to help make my SOTM-US presentation. I'm sitting at the hack day after the conference right now looking at one weird thing that popped up... Somehow the indexes and constraints aren't being created on initial import. It's getting to that point in the code and prints out a message about creating the constraints and indexes but they don't actually show up in the database. I don't see how your changes could have caused that though. Wondering if something in psycopg2 changed behind my back or something.

**Comment by ToeBee** [comment]
So it looks like there is no commit being called after the index/constraint creation. I swear this used to work though. Also in Oracle, DDL statements like that immediately auto-commit so that threw me off the trail for a while. But yeah, that isn't related to your changes.

One other issue I had was that there are 94 rows with invalid geometries. This is bad data coming from OSM. The lat/lon values are like 214.something. But this could be a pain when you're trying to do spatial queries. Should there maybe be a query to null out the geometry on these 94 rows after an initial file load? They are all old changesets and whatever bug created them seems to have been fixed so I don't think we will see new ones coming in through replication.

**Comment by ToeBee** [comment]
In talking with @pnorman it seems the index/constraint creation has **not** been working like I thought! So it is confirmed: this has nothing to do with this pull request.

**Pull request merged**
