### PR TITLE
Adding commandline capabilities & making script more dependent on standard python library modules

### PR DESCRIPTION
**Pull request by kristenkam**
Part of these commits is associated with the following reported issues:

https://github.com/ToeBee/ChangesetMD/issues/12
https://github.com/ToeBee/ChangesetMD/issues/13

### CODE REVIEW

**Comment by kristenkam** [comment]
@ToeBee , I went ahead and updated the logic to include the getpass module and get user method. Thanks for the feedback.

**Comment by kristenkam** [comment]
No. If you set the argument parser to default to "None" port value, you'll have an error:

>>> connection = psycopg2.connect("dbname=changesets user=postgres password=postgres host=localhost port=None")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\psycopg2\__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: invalid port number: "None"


You must specify an integer number. Way that doesn't cause the psycopg2 to break:

>>> connection = psycopg2.connect("dbname=changesets user=postgres password=postgres host=localhost port=5433")

**Comment by kristenkam** [comment]
So at the compilation of postgres, the default port is 5432. Which is why I had it default to 5432. NOW, if you have the default port to another value, that'd be specified with the PGPORT environmental variable. 

In python one could iterate through the environmental variables identfied here:

os.environ.keys()

If there is indeed a PGPORT environment (http://www.postgresql.org/docs/9.3/static/libpq-envars.html), then we could have that value be the port value used in the psycopg2.connect() methods.

Would adding logic for this also be acceptable?

**Comment by kristenkam** [comment]
@pnorman done!

**Comment by pnorman** [comment]
With no PGPORT set, it should default to whatever is compiled in libpq, which *may* be 5432. It may not.

But the problem with what you had in your comment is `connection = psycopg2.connect("dbname=changesets user=postgres password=postgres host=localhost port=None")` is completely different to how changesetmd calls connect with parameters instead of a conninfo string.

`conn = psycopg2.connect(database='gis', port=None)` works fine.

**Pull request merged**
